<?php
/**
 * @file
 * Code for the Bibsdb New Materials feature.
 */

include_once 'bibsdb_new_materials.features.inc';

/*
 * Public: Implements hook_form_FORM_ID_alter.
 *
 */
function bibsdb_new_materials_form_node_form_alter(&$form, $form_state) {
  $type = $form['#node']->type;

  if ('new_materials' == $type) {

  	// Hide field_ddelibra_search
  	$form['field_ddelibra_search']['#access'] = FALSE;

  	// Move up field_bibsdb_new_materials_image
  	$form['field_bibsdb_new_materials_image']['#weight'] = 2;
  }
}

/**
 * Public: Implements hook_ting_search_context_field_name().
 */
function bibsdb_new_materials_ting_search_context_field_name() {
  return array(
    'new_materials' => 'field_bibsdb_new_materials_image',
  );
}

